name: Self-assign issue
on:
  issues:
    types: [opened]
jobs:
  self-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Self-assign issue
        uses: peter-evans/self-assign@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
