name: Assign Reviewers on PR Write

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            const requested_reviewers = ['reviewer1', 'reviewer2']; // Add reviewers to this array
            await github.pulls.createReviewRequest({
              owner,
              repo,
              pull_number: number,
              reviewers: requested_reviewers
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
