name: Assign Reviewers on PR Write

on:
  pull_request:
    types: [opened, edited]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: actions/github-script@v5
        with:
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.payload.pull_request;
            const reviewers = ['Vikash-8090-Yadav']; 
            const pullRequestReviewRequest = {
              owner,
              repo,
              pull_number: number,
              reviewers,
            };
            await context.github.pulls.createReviewRequest(pullRequestReviewRequest);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
