name: Auto Assign Reviewer
on:
  pull_request:
  
jobs:
  assign_reviewer:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: shufo/auto-assign-reviewer-by-files@v1.1.4
        with:
          config: ".github/reviewers.yml"
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN1 }}
