name: "Auto Assign"
on:
  - pull_request

jobs:
  
  assign_reviewer:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: shufo/auto-assign-reviewer-by-files@v1.1.4
        with:
          config: ".github/reviewers.yml"
          token: ${{ secrets.TOKEN }}
